create table articles (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  meta_description text not null check (char_length(meta_description) <= 160),
  excerpt text not null,
  image_url text,
  created_at timestamptz not null default now()
);

create table offers (
  id bigint generated by default as identity primary key,
  brand text not null,
  categories text[] not null,
  code text not null,
  discount text not null,
  detail text not null,
  description text not null,
  created_at timestamptz not null default now()
);

create table coupon_clicks (
  id bigint generated by default as identity primary key,
  offer_id bigint references offers(id) on delete set null,
  brand text not null,
  created_at timestamptz not null default now()
);

create table sales (
  id bigint generated by default as identity primary key,
  brand text not null,
  amount numeric(10,2) not null check (amount > 0),
  commission numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);

alter table articles enable row level security;
alter table offers enable row level security;
alter table coupon_clicks enable row level security;
alter table sales enable row level security;

create policy "contenuti pubblici" on articles for select using (true);
create policy "offerte pubbliche" on offers for select using (true);

-- Estensioni necessarie per dashboard, articoli completi e coupon affiliati.
alter table articles add column if not exists slug text unique;
alter table articles add column if not exists content text not null default '';
alter table articles add column if not exists status text not null default 'published';
alter table articles drop constraint if exists articles_status_check;
alter table articles add constraint articles_status_check check (status in ('draft', 'scheduled', 'published'));
alter table articles add column if not exists scheduled_at timestamptz;
alter table offers add column if not exists affiliate_url text;
alter table offers add column if not exists expires_at date;
alter table offers add column if not exists active boolean not null default true;

create index if not exists articles_published_created_at_idx on articles (status, created_at desc);
create index if not exists coupon_clicks_created_at_idx on coupon_clicks (created_at desc);
