const http = require('http');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, 'outputs', 'wellness-sconti');
const dataDir = path.join(__dirname, 'data');
const port = Number(process.env.PORT) || 3000;
function ensure(name, fallback) { if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true }); const file = path.join(dataDir, name); if (!fs.existsSync(file)) fs.writeFileSync(file, JSON.stringify(fallback, null, 2)); return file; }
const offersFile = ensure('offers.json', [
  { id: 1, brand: 'Alo Yoga', category: ['yoga', 'activewear'], code: 'RITUALE10', discount: '10% di sconto', detail: 'Nuovi clienti', description: 'Il tuo nuovo set preferito, con un po’ di leggerezza in più.', theme: 'sage' },
  { id: 2, brand: 'BALM studio', category: ['pilates', 'wellness'], code: 'MOVEWITHUS', discount: '15% di sconto', detail: 'Su tutto il sito', description: 'Attrezzi essenziali per riportare la pratica a casa.', theme: 'clay' },
  { id: 3, brand: 'Oway', category: ['wellness'], code: 'RITUALE15', discount: '15% di sconto', detail: 'Primo ordine', description: 'Una routine più gentile, per te e per il pianeta.', theme: 'cream' },
  { id: 4, brand: 'Girlfriend Collective', category: ['activewear'], code: 'FLOW20', discount: '20% di sconto', detail: 'Selezione activewear', description: 'Activewear responsabile, fatto per seguirti ovunque.', theme: 'ink' },
  { id: 5, brand: 'Onda Pilates', category: ['pilates'], code: 'ONDA10', discount: '10% di sconto', detail: 'Corsi online', description: 'Dal reformer al tappetino: il movimento che ti somiglia.', theme: 'peach' },
  { id: 6, brand: 'Manduka', category: ['yoga', 'wellness'], code: 'CALMA12', discount: '12% di sconto', detail: 'Tappetini e blocchi', description: 'Un tappetino su cui tornare, ogni volta che ne hai bisogno.', theme: 'stone' }
]);
const articlesFile = ensure('articles.json', [
  { id: 1, title: 'Come scegliere il tappetino yoga giusto per te', category: 'Yoga', metaDescription: 'Materiali, spessore e grip: guida alla scelta del tappetino yoga.', excerpt: 'Materiali, spessore e grip: tutto quello che serve sapere prima di scegliere il tuo spazio di pratica.', createdAt: '2026-09-03T09:00:00.000Z' },
  { id: 2, title: 'Pilates a casa: cosa ti serve davvero per iniziare', category: 'Pilates', metaDescription: 'Gli accessori essenziali per iniziare pilates a casa.', excerpt: 'Poco spazio, pochi attrezzi, tanta costanza: il pilates può iniziare da qui.', createdAt: '2026-09-02T09:00:00.000Z' },
  { id: 3, title: '7 rituali lenti per chiudere la giornata', category: 'Wellness', metaDescription: 'Sette rituali serali semplici per rallentare e prepararsi al riposo.', excerpt: 'Piccoli segnali per dire al corpo: ora possiamo rallentare.', createdAt: '2026-09-01T09:00:00.000Z' }
]);
const subscribersFile = ensure('subscribers.json', []);
const analyticsFile = ensure('analytics.json', { clicks: [], sales: [] });
const sessions = new Set();
const adminPassword = process.env.ADMIN_PASSWORD || 'Rituale2026!';
const read = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const write = (file, data) => fs.writeFileSync(file, JSON.stringify(data, null, 2));
const send = (res, code, body) => { res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(body)); };
const body = req => new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => raw += chunk); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('JSON non valido')); } }); });
const staticFile = pathname => { const requested = pathname === '/' ? '/index.html' : decodeURIComponent(pathname); const file = path.normalize(path.join(root, requested)); return file.startsWith(root) ? file : null; };
const sessionFrom = req => (req.headers.cookie || '').match(/rituale_session=([^;]+)/)?.[1];
const authenticated = req => sessions.has(sessionFrom(req));
const requireAdmin = (req, res) => authenticated(req) || (send(res, 401, { error: 'Accesso riservato.' }), false);
http.createServer(async (req, res) => { const url = new URL(req.url, `http://${req.headers.host}`); try {
  const assets = { '/styles.css': ['styles.css', 'text/css; charset=utf-8'], '/script.js': ['script.js', 'text/javascript; charset=utf-8'] };
  if (req.method === 'GET' && assets[url.pathname]) { const [name, type] = assets[url.pathname]; const file = path.join(root, name); res.writeHead(200, { 'Content-Type': type, 'Cache-Control': 'no-store' }); return fs.createReadStream(file).pipe(res); }
  if (req.method === 'GET' && url.pathname === '/api/offers') return send(res, 200, read(offersFile));
  if (req.method === 'GET' && url.pathname === '/api/articles') return send(res, 200, read(articlesFile));
  if (req.method === 'POST' && url.pathname === '/api/track/click') { const input = await body(req); const analytics = read(analyticsFile); analytics.clicks.push({ offerId: Number(input.offerId) || null, brand: String(input.brand || ''), at: new Date().toISOString() }); write(analyticsFile, analytics); return send(res, 201, { ok: true }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/login') { const input = await body(req); if (input.password !== adminPassword) return send(res, 401, { error: 'Password non corretta.' }); const token = require('crypto').randomBytes(24).toString('hex'); sessions.add(token); res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8', 'Set-Cookie': `rituale_session=${token}; HttpOnly; SameSite=Lax; Path=/` }); return res.end(JSON.stringify({ message: 'Accesso effettuato.' })); }
  if (req.method === 'POST' && url.pathname === '/api/auth/logout') { sessions.delete(sessionFrom(req)); res.writeHead(204, { 'Set-Cookie': 'rituale_session=; HttpOnly; Max-Age=0; Path=/' }); return res.end(); }
  if (req.method === 'GET' && url.pathname === '/api/admin/session') return send(res, 200, { authenticated: authenticated(req) });
  if (req.method === 'GET' && url.pathname === '/api/admin/analytics') { if (!requireAdmin(req, res)) return; const analytics = read(analyticsFile); const today = new Date().toISOString().slice(0, 10); const clicks = analytics.clicks.length; const todayClicks = analytics.clicks.filter(item => item.at.slice(0, 10) === today).length; const sales = analytics.sales; return send(res, 200, { clicks, todayClicks, salesCount: sales.length, revenue: sales.reduce((sum, item) => sum + Number(item.amount || 0), 0), commissions: sales.reduce((sum, item) => sum + Number(item.commission || 0), 0), recentSales: sales.slice(-8).reverse() }); }
  if (req.method === 'POST' && url.pathname === '/api/admin/sales') { if (!requireAdmin(req, res)) return; const input = await body(req); if (!input.brand?.trim() || !Number(input.amount)) return send(res, 400, { error: 'Inserisci brand e valore della vendita.' }); const analytics = read(analyticsFile); analytics.sales.push({ id: Date.now(), brand: input.brand.trim(), amount: Number(input.amount), commission: Number(input.commission) || 0, at: new Date().toISOString() }); write(analyticsFile, analytics); return send(res, 201, { ok: true }); }
  if (req.method === 'POST' && url.pathname === '/api/articles') { if (!requireAdmin(req, res)) return; const input = await body(req); if (!input.title?.trim() || !input.category?.trim() || !input.metaDescription?.trim()) return send(res, 400, { error: 'Titolo, categoria e meta descrizione sono obbligatori.' }); if (input.metaDescription.length > 160) return send(res, 400, { error: 'La meta descrizione deve contenere al massimo 160 caratteri.' }); const articles = read(articlesFile); const article = { id: Date.now(), title: input.title.trim(), category: input.category.trim(), metaDescription: input.metaDescription.trim(), excerpt: input.excerpt?.trim() || input.metaDescription.trim(), createdAt: new Date().toISOString() }; articles.unshift(article); write(articlesFile, articles); return send(res, 201, article); }
  if (req.method === 'PUT' && /^\/api\/admin\/articles\/\d+$/.test(url.pathname)) { if (!requireAdmin(req, res)) return; const input = await body(req); const articles = read(articlesFile); const index = articles.findIndex(item => item.id === Number(url.pathname.split('/').pop())); if (index < 0) return send(res, 404, { error: 'Articolo non trovato.' }); articles[index] = { ...articles[index], title: input.title?.trim() || articles[index].title, category: input.category?.trim() || articles[index].category, metaDescription: input.metaDescription?.trim() || articles[index].metaDescription, excerpt: input.excerpt?.trim() || articles[index].excerpt }; write(articlesFile, articles); return send(res, 200, articles[index]); }
  if (req.method === 'DELETE' && /^\/api\/admin\/articles\/\d+$/.test(url.pathname)) { if (!requireAdmin(req, res)) return; const articles = read(articlesFile); const filtered = articles.filter(item => item.id !== Number(url.pathname.split('/').pop())); write(articlesFile, filtered); return send(res, 204, {}); }
  if (req.method === 'POST' && url.pathname === '/api/subscribers') { const { email = '' } = await body(req); if (!/^\S+@\S+\.\S+$/.test(email)) return send(res, 400, { error: 'Inserisci un indirizzo email valido.' }); const subscribers = read(subscribersFile); if (!subscribers.some(item => item.email === email.toLowerCase())) { subscribers.push({ email: email.toLowerCase(), subscribedAt: new Date().toISOString() }); write(subscribersFile, subscribers); } return send(res, 201, { message: 'Iscrizione registrata.' }); }
  const file = staticFile(url.pathname); if (!file || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404); return res.end('Pagina non trovata'); } const extension = path.extname(file); const type = extension === '.html' ? 'text/html' : extension === '.css' ? 'text/css' : extension === '.js' ? 'text/javascript' : 'application/octet-stream'; res.writeHead(200, { 'Content-Type': `${type}; charset=utf-8` }); fs.createReadStream(file).pipe(res);
} catch (error) { send(res, 500, { error: error.message || 'Errore del server.' }); } }).listen(port, () => console.log(`Rituale è attivo su http://localhost:${port}`));
