const crypto = require('crypto');
const send = (res, code, body) => res.status(code).json(body);
const env = name => { if (!process.env[name]) throw new Error(`Configurazione mancante: ${name}`); return process.env[name]; };
const image = category => ({ Yoga:'/assets/articles/yoga-tappetino-casa.png', Pilates:'/assets/articles/pilates-accessori-casa.png', Activewear:'/assets/articles/activewear-comfort.png', Wellness:'/assets/articles/wellness-rituale-serale.png' }[category] || '/assets/articles/wellness-rituale-serale.png');
async function db(table, options = {}) { const key=env('SUPABASE_SERVICE_ROLE_KEY'), base=env('SUPABASE_URL').replace(/\/$/, ''); const response=await fetch(`${base}/rest/v1/${table}${options.query||''}`,{method:options.method||'GET',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=representation'},body:options.body?JSON.stringify(options.body):undefined}); const text=await response.text(); if(!response.ok)throw new Error(`Database: ${text||response.status}`); return text?JSON.parse(text):null; }
function sig(value){return crypto.createHmac('sha256',env('ADMIN_SESSION_SECRET')).update(value).digest('base64url');}
function allowed(req){const token=(req.headers.cookie||'').match(/rituale_admin=([^;]+)/)?.[1];if(!token)return false;const [raw,sign]=token.split('.');try{return raw&&sign&&sign===sig(raw)&&JSON.parse(Buffer.from(raw,'base64url').toString()).expiresAt>Date.now();}catch{return false;}}
function guard(req,res){if(allowed(req))return true;send(res,401,{error:'Accesso riservato.'});return false;}
function session(res){const raw=Buffer.from(JSON.stringify({expiresAt:Date.now()+43200000})).toString('base64url');res.setHeader('Set-Cookie',`rituale_admin=${raw}.${sig(raw)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=43200`);}
async function automatedArticles(){const prompt='Scrivi 4 articoli SEO originali in italiano, uno per Yoga, Pilates, Activewear e Wellness. Rispondi soltanto JSON: {"articles":[{"category":"Yoga","title":"","meta_description":"max 155 caratteri","excerpt":"max 280 caratteri","content":"700-900 parole con titoletti Markdown"}]}. Non fare promesse mediche o affermazioni non verificabili.';const response=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env('OPENAI_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4.1-mini',response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message||'Generazione non riuscita.');const records=JSON.parse(result.choices[0].message.content).articles;if(!Array.isArray(records)||records.length!==4)throw new Error('Non sono stati creati quattro articoli.');const rows=records.map(a=>({title:String(a.title||'').slice(0,150),category:['Yoga','Pilates','Activewear','Wellness'].includes(a.category)?a.category:'Wellness',meta_description:String(a.meta_description||'').slice(0,160),excerpt:String(a.excerpt||'').slice(0,300),content:String(a.content||''),image_url:image(a.category),status:'published'})).filter(a=>a.title&&a.meta_description&&a.content);if(rows.length!==4)throw new Error('Articoli incompleti.');return db('articles',{method:'POST',body:rows});}
module.exports=async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,body=typeof req.body==='object'&&req.body?req.body:{};
if(req.method==='GET'&&path==='/api/public/offers')return send(res,200,await db('offers',{query:'?select=*&active=eq.true&order=created_at.desc'}));
if(req.method==='GET'&&path==='/api/public/articles')return send(res,200,await db('articles',{query:'?select=id,slug,title,category,meta_description,excerpt,content,image_url,created_at&status=eq.published&order=created_at.desc&limit=12'}));
if(req.method==='POST'&&path==='/api/track/click'){await db('coupon_clicks',{method:'POST',body:{offer_id:body.offerId||null,brand:String(body.brand||'Sconosciuto').slice(0,100)}});return send(res,201,{ok:true});}
if(req.method==='POST'&&path==='/api/admin/login'){if(body.password!==env('ADMIN_PASSWORD'))return send(res,401,{error:'Password non corretta.'});session(res);return send(res,200,{ok:true});}
if(req.method==='POST'&&path==='/api/admin/logout'){res.setHeader('Set-Cookie','rituale_admin=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');return send(res,200,{ok:true});}
if(req.method==='GET'&&path==='/api/admin/dashboard'){if(!guard(req,res))return;const [clicks,sales,offers,articles]=await Promise.all([db('coupon_clicks',{query:'?select=created_at&limit=5000'}),db('sales',{query:'?select=brand,amount,commission,created_at&order=created_at.desc&limit=20'}),db('offers',{query:'?select=id&active=eq.true'}),db('articles',{query:'?select=id&status=eq.published'})]);const today=new Date().toISOString().slice(0,10);return send(res,200,{clicks:clicks.length,todayClicks:clicks.filter(x=>x.created_at.slice(0,10)===today).length,salesCount:sales.length,revenue:sales.reduce((s,x)=>s+Number(x.amount||0),0),commissions:sales.reduce((s,x)=>s+Number(x.commission||0),0),activeOffers:offers.length,publishedArticles:articles.length,recentSales:sales.slice(0,6)});}
if(req.method==='POST'&&path==='/api/admin/offers'){if(!guard(req,res))return;if(!body.brand||!body.code||!body.discount)return send(res,400,{error:'Brand, codice e sconto sono obbligatori.'});return send(res,201,(await db('offers',{method:'POST',body:{brand:String(body.brand),categories:Array.isArray(body.categories)?body.categories:['wellness'],code:String(body.code).toUpperCase(),discount:String(body.discount),detail:String(body.detail||''),description:String(body.description||''),affiliate_url:String(body.affiliate_url||''),expires_at:body.expires_at||null,active:true}}))[0]);}
if(req.method==='POST'&&path==='/api/admin/articles'){if(!guard(req,res))return;if(!body.title||!body.meta_description||!body.content)return send(res,400,{error:'Titolo, meta descrizione e testo sono obbligatori.'});const category=body.category||'Wellness';return send(res,201,(await db('articles',{method:'POST',body:{title:String(body.title),category,meta_description:String(body.meta_description).slice(0,160),excerpt:String(body.excerpt||body.meta_description).slice(0,300),content:String(body.content),image_url:body.image_url||image(category),status:'published'}}))[0]);}
if(req.method==='POST'&&path==='/api/admin/sales'){if(!guard(req,res))return;if(!body.brand||!Number(body.amount))return send(res,400,{error:'Brand e valore vendita sono obbligatori.'});return send(res,201,(await db('sales',{method:'POST',body:{brand:String(body.brand),amount:Number(body.amount),commission:Number(body.commission||0)}}))[0]);}
if(req.method==='GET'&&path==='/api/cron/publish'){if(req.headers.authorization!==`Bearer ${env('CRON_SECRET')}`)return send(res,401,{error:'Non autorizzato.'});const published=await db('articles',{method:'PATCH',query:`?status=eq.scheduled&scheduled_at=lte.${encodeURIComponent(new Date().toISOString())}`,body:{status:'published'}});return send(res,200,{published:published.length});}
return send(res,404,{error:'Endpoint non trovato.'});}catch(error){return send(res,500,{error:error.message||'Errore interno.'});}};
